[package]
name = "blitz-host-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Local Unix domain socket transport and discovery for blitz-host"

[dependencies]
blitz-host-protocol = { version = "0.1.2", path = "../blitz-host-protocol" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
